// Mock data for CitiZen platform

export const wasteCategories = [
  {
    id: "minyak-jelantah",
    name: "Minyak Jelantah",
    conversion: "Biodiesel",
    icon: "droplet",
    estimasi: "Rp 3.000–8.000 / liter",
    outputs: ["Biodiesel", "Bahan bakar alternatif", "Sabun daur ulang"],
  },
  {
    id: "limbah-organik",
    name: "Limbah Organik",
    conversion: "Kompos / Pakan",
    icon: "leaf",
    estimasi: "Rp 500–2.000 / kg",
    outputs: ["Kompos premium", "Pakan ternak", "Biogas"],
  },
  {
    id: "cangkang-seafood",
    name: "Cangkang Seafood",
    conversion: "Pupuk / Material",
    icon: "shell",
    estimasi: "Rp 1.000–5.000 / kg",
    outputs: ["Pupuk kalsium", "Material bangunan", "Pakan unggas"],
  },
  {
    id: "plastik-hdpe",
    name: "Plastik HDPE",
    conversion: "Daur Ulang",
    icon: "recycle",
    estimasi: "Rp 2.000–6.000 / kg",
    outputs: ["Biji plastik daur ulang", "Pipa PVC", "Wadah industri"],
  },
  {
    id: "serbuk-kayu",
    name: "Serbuk Kayu",
    conversion: "Briket / Papan",
    icon: "tree",
    estimasi: "Rp 500–3.000 / kg",
    outputs: ["Briket arang", "Papan partikel", "Media tanam"],
  },
  {
    id: "lainnya",
    name: "Lainnya",
    conversion: "Beragam",
    icon: "package",
    estimasi: "Bervariasi",
    outputs: ["Beragam produk olahan"],
  },
];

export const mockListings = [
  {
    id: "1",
    title: "Minyak Jelantah Restoran",
    category: "Minyak Jelantah",
    categoryId: "minyak-jelantah",
    volume: "50 liter",
    city: "Surabaya",
    price: "Rp 5.000/liter",
    priceNum: 5000,
    status: "Tersedia",
    seller: "Warung Seafood Pak Budi",
    sellerCity: "Surabaya",
    memberSince: "Jan 2025",
    rating: 4.8,
    description:
      "Minyak jelantah bekas dari restoran seafood. Sudah disaring dan disimpan dalam jeriken 10 liter. Cocok untuk diolah menjadi biodiesel atau sabun.",
    datePosted: "2 hari lalu",
  },
  {
    id: "2",
    title: "Ampas Tahu Segar",
    category: "Limbah Organik",
    categoryId: "limbah-organik",
    volume: "200 kg",
    city: "Bandung",
    price: "Rp 800/kg",
    priceNum: 800,
    status: "Tersedia",
    seller: "Pabrik Tahu Bu Sri",
    sellerCity: "Bandung",
    memberSince: "Mar 2025",
    rating: 4.5,
    description:
      "Ampas tahu segar harian dari produksi tahu. Bisa diambil setiap hari jam 6-8 pagi. Cocok untuk pakan ternak atau kompos.",
    datePosted: "1 hari lalu",
  },
  {
    id: "3",
    title: "Cangkang Kerang Hijau",
    category: "Cangkang Seafood",
    categoryId: "cangkang-seafood",
    volume: "100 kg",
    city: "Jakarta",
    price: "Rp 2.500/kg",
    priceNum: 2500,
    status: "Dalam Nego",
    seller: "Pasar Seafood Muara Angke",
    sellerCity: "Jakarta",
    memberSince: "Feb 2025",
    rating: 4.2,
    description:
      "Cangkang kerang hijau bersih, sudah dicuci. Bisa diolah menjadi pupuk kalsium atau material bangunan tambahan.",
    datePosted: "3 hari lalu",
  },
  {
    id: "4",
    title: "Botol Plastik HDPE Bersih",
    category: "Plastik HDPE",
    categoryId: "plastik-hdpe",
    volume: "80 kg",
    city: "Medan",
    price: "Rp 4.000/kg",
    priceNum: 4000,
    status: "Tersedia",
    seller: "Bank Sampah Medan Hijau",
    sellerCity: "Medan",
    memberSince: "Dec 2024",
    rating: 4.9,
    description:
      "Botol HDPE yang sudah dicuci bersih dan dipres. Siap untuk daur ulang menjadi biji plastik.",
    datePosted: "Hari ini",
  },
  {
    id: "5",
    title: "Serbuk Kayu Jati",
    category: "Serbuk Kayu",
    categoryId: "serbuk-kayu",
    volume: "500 kg",
    city: "Surabaya",
    price: "Rp 1.500/kg",
    priceNum: 1500,
    status: "Tersedia",
    seller: "UD Mebel Jaya",
    sellerCity: "Surabaya",
    memberSince: "Jun 2025",
    rating: 4.6,
    description:
      "Serbuk kayu jati halus dari produksi furnitur. Cocok untuk briket, media tanam, atau papan partikel.",
    datePosted: "5 hari lalu",
  },
  {
    id: "6",
    title: "Minyak Goreng Bekas",
    category: "Minyak Jelantah",
    categoryId: "minyak-jelantah",
    volume: "30 liter",
    city: "Makassar",
    price: "Rp 4.500/liter",
    priceNum: 4500,
    status: "Terjual",
    seller: "Warung Makan Ibu Ani",
    sellerCity: "Makassar",
    memberSince: "Apr 2025",
    rating: 4.3,
    description:
      "Minyak goreng bekas dari warung makan. Dikumpulkan setiap minggu dalam total sekitar 30 liter.",
    datePosted: "1 minggu lalu",
  },
  {
    id: "7",
    title: "Kulit Udang Kering",
    category: "Cangkang Seafood",
    categoryId: "cangkang-seafood",
    volume: "60 kg",
    city: "Surabaya",
    price: "Rp 3.000/kg",
    priceNum: 3000,
    status: "Tersedia",
    seller: "Pabrik Kerupuk Sidoarjo",
    sellerCity: "Surabaya",
    memberSince: "May 2025",
    rating: 4.7,
    description:
      "Kulit udang yang sudah dikeringkan. Bisa diolah menjadi chitosan, pakan, atau pupuk organik.",
    datePosted: "2 hari lalu",
  },
  {
    id: "8",
    title: "Sampah Sayuran Pasar",
    category: "Limbah Organik",
    categoryId: "limbah-organik",
    volume: "300 kg",
    city: "Jakarta",
    price: "Gratis",
    priceNum: 0,
    status: "Tersedia",
    seller: "Pasar Induk Kramat Jati",
    sellerCity: "Jakarta",
    memberSince: "Jan 2025",
    rating: 4.0,
    description:
      "Limbah sayuran segar dari pasar induk. Tersedia setiap hari dalam jumlah besar. Gratis untuk yang mengambil sendiri.",
    datePosted: "Hari ini",
  },
  {
    id: "9",
    title: "Drum Plastik HDPE Bekas",
    category: "Plastik HDPE",
    categoryId: "plastik-hdpe",
    volume: "20 unit",
    city: "Bandung",
    price: "Rp 25.000/unit",
    priceNum: 25000,
    status: "Dalam Nego",
    seller: "PT Kimia Farma Distribusi",
    sellerCity: "Bandung",
    memberSince: "Aug 2025",
    rating: 4.4,
    description:
      "Drum plastik HDPE bekas kemasan bahan kimia non-berbahaya. Sudah dicuci bersih, volume 200L per drum.",
    datePosted: "4 hari lalu",
  },
];

export const mockNeeds = [
  {
    id: "1",
    company: "GreenFuel Indonesia",
    city: "Jakarta",
    category: "Minyak Jelantah",
    categoryId: "minyak-jelantah",
    volume: "500 liter/bulan",
    frequency: "Rutin Bulanan",
    price: "Rp 6.000/liter",
    description: "Membutuhkan minyak jelantah untuk produksi biodiesel B30.",
  },
  {
    id: "2",
    company: "PT Kompos Nusantara",
    city: "Surabaya",
    category: "Limbah Organik",
    categoryId: "limbah-organik",
    volume: "1 ton/bulan",
    frequency: "Rutin Bulanan",
    price: "Rp 1.000/kg",
    description: "Membutuhkan limbah organik segar untuk produksi kompos premium.",
  },
  {
    id: "3",
    company: "CV Plastik Jaya Mandiri",
    city: "Bandung",
    category: "Plastik HDPE",
    categoryId: "plastik-hdpe",
    volume: "200 kg",
    frequency: "Sekali",
    price: "Rp 5.000/kg",
    description: "Cari plastik HDPE bersih untuk daur ulang menjadi biji plastik.",
  },
  {
    id: "4",
    company: "PT Briket Energi",
    city: "Medan",
    category: "Serbuk Kayu",
    categoryId: "serbuk-kayu",
    volume: "2 ton/bulan",
    frequency: "Rutin Bulanan",
    price: "Rp 2.000/kg",
    description:
      "Membutuhkan serbuk kayu untuk produksi briket arang ekspor.",
  },
  {
    id: "5",
    company: "Peternakan Maju Bersama",
    city: "Makassar",
    category: "Cangkang Seafood",
    categoryId: "cangkang-seafood",
    volume: "300 kg/bulan",
    frequency: "Rutin Bulanan",
    price: "Rp 2.000/kg",
    description:
      "Membutuhkan cangkang kerang/udang untuk campuran pakan unggas.",
  },
  {
    id: "6",
    company: "EcoSoap Cooperative",
    city: "Surabaya",
    category: "Minyak Jelantah",
    categoryId: "minyak-jelantah",
    volume: "100 liter",
    frequency: "Sekali",
    price: "Rp 5.500/liter",
    description:
      "Membutuhkan minyak jelantah untuk workshop pembuatan sabun komunitas.",
  },
];

export const testimonials = [
  {
    name: "Budi Warsito",
    role: "Warung Seafood Surabaya",
    initials: "BW",
    quote:
      "Dulu minyak bekas dibuang ke got, sekarang dapat Rp 400rb dari limbah doang.",
  },
  {
    name: "Rini Pratiwi",
    role: "Procurement Manager GreenFuel Co.",
    initials: "RP",
    quote:
      "Dalam seminggu sudah ada 12 UMKM yang respond. Jauh lebih mudah.",
  },
  {
    name: "Sri Rahayu",
    role: "Produsen Tahu Bandung",
    initials: "SR",
    quote:
      "Ampas tahu saya langsung dibeli peternak. Platformnya gampang dipakai.",
  },
];

export const dashboardListings = [
  {
    id: "1",
    name: "Minyak Jelantah Restoran",
    category: "Minyak Jelantah",
    volume: "50 liter",
    price: "Rp 5.000/liter",
    status: "Tersedia",
  },
  {
    id: "2",
    name: "Serbuk Kayu Jati",
    category: "Serbuk Kayu",
    volume: "500 kg",
    price: "Rp 1.500/kg",
    status: "Tersedia",
  },
  {
    id: "3",
    name: "Kulit Udang Kering",
    category: "Cangkang Seafood",
    volume: "60 kg",
    price: "Rp 3.000/kg",
    status: "Dalam Nego",
  },
  {
    id: "4",
    name: "Ampas Tahu Harian",
    category: "Limbah Organik",
    volume: "200 kg",
    price: "Rp 800/kg",
    status: "Terjual",
  },
  {
    id: "5",
    name: "Botol Plastik Bersih",
    category: "Plastik HDPE",
    volume: "80 kg",
    price: "Rp 4.000/kg",
    status: "Tersedia",
  },
];

export const cities = ["Jakarta", "Surabaya", "Bandung", "Medan", "Makassar"];
